### PR TITLE
Add autoscaler setup CLI and docs

### PR DESCRIPTION
**Pull request by aluminiumgeek**
- Setup autoscaler on cluster
- Update docs

### CODE REVIEW

**Comment by rufuspollock** [comment]
@aluminiumgeek can you check why build failed here.

**Comment by rufuspollock** [comment]
@aluminiumgeek please can you look at this asap please 😄

**Comment by aluminiumgeek** [comment]
Build is failing because the PR is compared to the code in my own repo (it was created before I've got write access to this repo). I'll close this one and open the new one

**Comment by aluminiumgeek** [comment]
The code is already in `master`

**Pull request closed without merging**
